### ISSUE TITLE
DE GSM not functional for QChem

### ISSUE THREAD

**Issue by kspieks** [ZimmermanGroup/pyGSM#15]
Hi Cody, 

Can you please help me test pyGSM for QChem? There were a few minor errors in the current master branch. I tried fixing some locally, but I figure you have a better idea of how many more changes are necessary. I would appreciate your help to run further tests to ensure DE GSM is functional with QChem. 

Thanks,
Kevin

**Comment by craldaz** [comment]
Just wanted to let you know I received this, an I'll take a look at this soon. Sorry for the delay.

**Comment by kspieks** [comment]
No worries. Thanks for looking into it.

**Comment by craldaz** [comment]
I don't have access to Q-Chem, but I did spot a few errors in Q-Chem a while back that I fixed. I think it should be fixed but I don't have a way of checking.
