### ISSUE TITLE
For now if the DLC work?

### ISSUE THREAD

**Issue by ms860309** [ZimmermanGroup/pyGSM#4]
When i use the default coordinate_type TRIC it work pretty well, but DLC type i encounter the following error message
`Traceback (most recent call last):
  File "/home/guest/guest94/anaconda3/envs/gsm_env/bin/gsm", line 11, in <module>
    load_entry_point('pyGSM==0.1', 'console_scripts', 'gsm')()
  File "/home/guest/guest94/jianyi/pyGSM/pygsm/wrappers/main.py", line 338, in main
    frozen_atoms=frozen_indices,
  File "/home/guest/guest94/jianyi/pyGSM/pygsm/coordinate_systems/internal_coordinates.py", line 133, in from_options
    return cls(cls.default_options().set_values(kwargs))
  File "/home/guest/guest94/jianyi/pyGSM/pygsm/coordinate_systems/primitive_internals.py", line 79, in __init__
    self.newMakePrimitives(xyz)
  File "/home/guest/guest94/jianyi/pyGSM/pygsm/coordinate_systems/primitive_internals.py", line 734, in newMakePrimitives
    AtomIterator, dxij = self.distance_matrix(xyz,pbc=False)
AttributeError: 'PrimitiveInternalCoordinates' object has no attribute 'distance_matrix'`

Thanks for answering!!

**Comment by craldaz** [comment]
DLC works for me. Perhaps some user error? What are your input arguments to gsm?

**Comment by ms860309** [comment]
Hi, my gsm command(success) is "gsm -xyzfile {} -mode SE_GSM -package QChem
-isomers {} -lot_inp_file {}"  and it will run TRIC" as default.
Butwhen i use "gsm -xyzfile {} -mode SE_GSM -package QChem -isomers {}
-lot_inp_file {} -coordinate_type DLC"
It return me the following file.
I try the same file(7) in TRIC, about half of them are success.
If there are some special parameters that i forgot to set for DLC?

By the way, in some cases i encounter the this error message (this input
file I will upload in the attach file  prob.zip)
"""
Traceback (most recent call last):
  File
"/home/guest/guest94/anaconda3/envs/gsm_env/lib/python3.7/site-packages/pyGSM-0.1-py3.7.egg/pygsm/coordinate_systems/primitive_internals.py",
line 1272, in get_hybrid_indices
    new_hybrid_indices.remove(elem)
ValueError: list.remove(x): x not in list
"""

Thanks for the help!!
craldaz <notifications@github.com> 於 2020年3月17日 週二 上午4:39寫道：

**Comment by ms860309** [comment]
Oh, sorry in prob.zip
I think my code have some bugs..
Could you please give me an example for running DLC type.
If the example contain add and break bonds driving coordinate would be
better.
thank you

李建毅 <ms860309@gmail.com>於 2020年3月17日 週二，下午1:12寫道：

**Comment by craldaz** [comment]
I think there was a bug in Topology which wasn't showing up in my local build. Will be pushing an update soon.

**Comment by craldaz** [comment]
This issue should
